feat: add challenge list api
today-they-learned/peacepiece_api pull request #18
Opened 2022-08-02 17:48 UTC by Jin409

challenge list 를 뽑아주는 api 를 구성했습니다.

수정해야 할 사항들 알려주세요!

2022-08-02 23:45 UTC, Jihyun-Choi reviewed
지금 깨달았는데 저희... 왜 migrations파일이 없을까요...? ....?
`python manage.py makemigrations` 진행하셨나요?

2022-08-02 23:45 UTC, Jihyun-Choi commented on config/urls.py
> +    path('api/challenge/',include('challenge.urls')),
혹시 pre-commit 적용되고 있나요?

2022-08-03 12:53 UTC, Jihyun-Choi commented on challenge/serializers/mission_serializer.py
> +    fields = "__all__"
위에는 fields, read_only_fields 로 각각 지정 해주셨는데 여기는 왜 `fields = "__all__"`로 두셨나요??

2022-08-03 14:24 UTC, shinkeonkim commented on challenge/serializers/category_serializer.py
> +    fields = "__all__"
p1. fields 랑 read_only_fields를 명시하는게 좋을 것 같아요

2022-08-03 14:25 UTC, shinkeonkim commented on challenge/views/challenge_retrieve_api_view.py
> +    search_fields = ['start_at', 'end_at']
p1: DjangoFilterBackend를 쓰고 filterset_fields=['start_at', 'end_at'] 으로 넣어보시겠어요?

2022-08-03 14:26 UTC, shinkeonkim commented on challenge/views/challenge_retrieve_api_view.py
> +        return Response(serializer.data)
p1: 굳이 오버라이딩 안해도 될 것 같습니다. DjangoFilterBackend 쓰고, filterset_fields에 'category'를 추가해주세요. 동일한 역할입니다.

2022-08-03 14:27 UTC, shinkeonkim requested changes
코멘트 확인부탁드려요

2022-08-03 14:34 UTC, Jin409 commented
> 지금 깨달았는데 저희... 왜 migrations파일이 없을까요...? ....? `python manage.py makemigrations` 진행하셨나요?
> 
> djangofilterbackend 를 이용하다가 삭제하신 이유는 무엇인가요?

현재 코드에서 searchFilter 를 사용해서 굳이 djangofilterbackend 를 안써도 될 것 같다는 판단 하에 다시 뗐습니다

2022-08-03 14:46 UTC, Jin409 commented on challenge/views/challenge_retrieve_api_view.py
> +        return Response(serializer.data)
제 궁금증인데 그렇게 될 경우 쿼리스트링에 category의 이름을 넣으면 검색이 안되는 것 아닌가요? 객체 자체로 찾는 것일까요?

2022-08-04 16:32 UTC, merged