feat: feedback 관련 모델 구현
today-they-learned/peacepiece_api pull request #75
Opened 2022-08-31 15:59 UTC by Jin409

## 작업 내용
- feedback 과 관련된 모델들을 전부 구현했습니다.

## 기타 사항
- article_user_feedbacks 의 경우에는 admin 에서 user 필드를 read_only 로 하려고 했는데, 그렇게 했더니 user_id 가 안넘어가서 null 이라고 오류를 발생시키더라고요.. 그래서 임시로 read_only 를 빼놨는데 관련해서 다른 해결방법 있으면 공유 부탁드립니다!

2022-08-31 16:25 UTC, Jihyun-Choi approved these changes
확인했습니다!

2022-08-31 16:39 UTC, shinkeonkim commented
> article_user_feedbacks 의 경우에는 admin 에서 user 필드를 read_only 로 하려고 했는데, 그렇게 했더니 user_id 가 안넘어가서 null 이라고 오류를 발생시키더라고요.. 그래서 임시로 read_only 를 빼놨는데 관련해서 다른 해결방법 있으면 공유 부탁드립니다!

크게 상관없을 것 같습니다. 사실 어드민에서 해당 레코드를 생성/수정하지는 않을테니, 해당 오류를 볼 일도 없을 것 같습니다

2022-08-31 16:41 UTC, shinkeonkim commented on feedback/models/article_feedback.py
> +        related_name='feedbacks',
```suggestion
        related_name='article_feedbacks',
```

2022-08-31 16:41 UTC, shinkeonkim commented on feedback/models/article_feedback.py
> +        related_name='feedbacks',
```suggestion
        related_name='article_feedbacks',
```

2022-08-31 16:41 UTC, shinkeonkim commented on feedback/models/article_user_feedback.py
> +        related_name='user_feedbacks',
```suggestion
        related_name='article_user_feedbacks',
```

2022-08-31 16:42 UTC, shinkeonkim commented on feedback/models/article_user_feedback.py
> +        related_name='user_feedbacks',
```suggestion
        related_name='article_user_feedbacks',
```

2022-08-31 16:42 UTC, shinkeonkim commented on feedback/models/article_user_feedback.py
> +        related_name='user_feedbacks',
```suggestion
        related_name='article_user_feedbacks',
```

2022-08-31 16:43 UTC, shinkeonkim requested changes
리뷰 내용 확인/수정 부탁드립니다

2022-09-01 10:58 UTC, shinkeonkim commented on feedback/models/article_user_feedback.py
> +        related_name='user_feedbacks',
@Jin409 요건 왜 반영이 안된걸까유?

2022-09-01 10:59 UTC, shinkeonkim commented on feedback/migrations/0001_initial.py
> +                ('count', models.PositiveIntegerField(default=0)),
로컬에서 디비 마이그레이션 롤백하고 다시 마이그레이션 만드셨나보네요? (혹은 db 파일 삭제하고 했거나?)

2022-09-02 12:22 UTC, Jin409 commented on feedback/migrations/0001_initial.py
> +                ('count', models.PositiveIntegerField(default=0)),
> 로컬에서 디비 마이그레이션 롤백하고 다시 마이그레이션 만드셨나보네요? (혹은 db 파일 삭제하고 했거나?)

헉.. 네 그러면 꼬이려나요?

2022-09-02 13:11 UTC, shinkeonkim commented on feedback/migrations/0001_initial.py
> +                ('count', models.PositiveIntegerField(default=0)),
저희는 안꼬이는데, 승희님 로컬이 꼬여있을까봐요 ㅋㅋ
지우시고 하셨으면 뭐 괜찮겠네요

2022-09-02 13:12 UTC, shinkeonkim commented on feedback/models/article_user_feedback.py
> +        related_name='user_feedbacks',
@Jin409 요거 봐주세요 ㅠㅠㅠ

2022-09-03 06:02 UTC, Jihyun-Choi submitted a review, later dismissed
수고하셨습니당:)

2022-09-03 09:42 UTC, shinkeonkim approved these changes

2022-09-03 09:42 UTC, merged