feat: notification 모델 수정
today-they-learned/peacepiece_api pull request #88
Opened 2022-09-07 14:15 UTC by Jin409

## 작업 내용
- notification 모델 수정했습니다.

## 기타 사항
- null=True 로 두는게 맞을까요..?

2022-09-07 14:59 UTC, Jihyun-Choi approved these changes
:)

2022-09-07 14:59 UTC, Jihyun-Choi commented on notification/models/notification.py
> +
p5? 아까 신건님이 예시들어주셨(?)었지만 IntegerField로 숫자로 처리하는것보단 CharField로 "challenge", "piece", "category"로 처리했다면 조금 더 명확하지 않았을까란 개인적인 생각이 들었슴다

2022-09-07 14:59 UTC, Jihyun-Choi commented on notification/models/notification.py
>  class Notification(models.Model):
이거 제가 예전에 만들었던 모델인데 그때는 cofig에 BaseModel이 없어서 요롷게 해뒀는데, BaseModel 상속하도록 수정해서 created_at, updated_at 삭제해도 되지 않을까요 ?!

2022-09-08 08:09 UTC, shinkeonkim commented on notification/models/notification.py
> +
저도 좋은 것 같습니다 ㅎㅎ

2022-09-08 08:09 UTC, shinkeonkim commented on notification/models/notification.py
>  class Notification(models.Model):
BaseModel을 상속받는게 더 좋을 것 같습니다

2022-09-08 08:10 UTC, shinkeonkim approved these changes
좋습니다. 지현님이 남겨주신 리뷰내용 반영해주시면 될 것 같아욥

2022-09-08 10:53 UTC, Jihyun-Choi approved these changes
굿굿 :)

2022-09-08 12:40 UTC, shinkeonkim requested changes
카테고리가 IntegerField로 되어있는데요? CharField가 되어야 할 것 같아요

2022-09-08 12:40 UTC, Jin409 commented
> 카테고리가 IntegerField로 되어있는데요? CharField가 되어야 할 것 같아요

으악.. 죄송함다 바로 수정할게요

2022-09-08 12:42 UTC, shinkeonkim commented
어드민에서 작동하는지 테스트하고 올려주세욥

2022-09-08 14:10 UTC, shinkeonkim submitted a review, later dismissed
좋습니다

2022-09-08 14:20 UTC, shinkeonkim approved these changes
LGTM

2022-09-08 16:47 UTC, merged